### ISSUE TITLE
charonctl panic when no args supplied

### ISSUE THREAD

**Issue by warmans** [piotrkowalczuk/charon#16]
This could fail more gracefully: 

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.(*configuration).parse(0xb996e0)
	/home/swarman/go/src/github.com/piotrkowalczuk/charon/charonctl/config.go:42 +0x9e
main.main()
	/home/swarman/go/src/github.com/piotrkowalczuk/charon/charonctl/main.go:23 +0x2f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 6 [runnable]:
text/template/parse.lexText(0xc8200ca680, 0x9fce50)
	/usr/local/go/src/text/template/parse/lex.go:237 +0x37e
text/template/parse.(*lexer).run(0xc8200ca680)
	/usr/local/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
```

**Comment by piotrkowalczuk** [comment]
kind of done, not a final state
